#!/usr/bin/env php
<?php
declare(strict_types=1);

require_once __DIR__.'/vendor/autoload.php';

use Zikula\Bundle\GeneratorBundle\Application;

$application = new Application();
$application->run();
