#!/usr/bin/env php
<?php

declare(strict_types=1);

use Zikula\Bundle\GeneratorBundle\Application;
use Symfony\Component\Console\Input\ArgvInput;

set_time_limit(0);

$loader = require __DIR__.'/../vendor/autoload.php';
require_once __DIR__.'/AppKernel.php';

$input = new ArgvInput();
$env = $input->getParameterOption(['--env', '-e'], getenv('ZIKULA_ENV') ?: 'dev');
$debug = getenv('ZIKULA_DEBUG') !== '0' && !$input->hasParameterOption(['--no-debug', '']) && $env !== 'prod';

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->run($input);
